---
title: "Single-cell RNA-seq analysis of single species"
author: "Yasir Arafat Tamal"
date: "9/15/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


### **Summary of input data**
Cellular gene expression profiles were generated from the developing leaf primordia, an embryonic tissue that gives rise to leaves, of wild-type C. hirsuta, a closely related species to the model A. thaliana. The C. hirsuta plants were grown in the soil in a greenhouse under short-day conditions (18°C in 16 hours dark and 21°C in 8 hours light), and leaves 5, 6, and 7 were collected at three weeks post-germination. Four biological replicates were collected, and the 10x Genomics scRNA-seq protocol was used to generate transcriptomic profiles at the single-cell level. The scRNA-seq datasets of C. hirsuta contain gene expression profiles of 4100, 6640, 9090, and 10760 cells with an average median of 5195 genes and an average median of 21,637 unique molecular identifier (UMI) counts per cell. The C. hirsuta reference genome contains a total of 27,773 genes.

